### ISSUE TITLE
Resources can't be found on Windows due to use of File.separator

### ISSUE THREAD

**Issue by jskeet** [googleapis/api-compiler#19]
Running the toolkit runCodeGen Gradle task on Windows, I get an error:

> top level:1: cannot open source 'auth_document.snip': java.lang.IllegalArgumentException: resource com/google/api/tools/framework/aspects/authentication/snippet\auth_document.snip not found.

Note the backslash at the end. This is due to the use of `File.separator` in [SnippetSet.resourceInputSupplier](https://github.com/googleapis/api-compiler/blob/1f859c54ad055e6d958ee159c16fca7dd965c030/src/main/java/com/google/api/tools/framework/snippet/SnippetSet.java#L437).

This should just use a `/` as that's always the separator in resource names - while a backslash may work while loading straight from the file system, it won't work when the resource is loaded from a jar file.

There are *lots* of uses of `File.separator` in this repo - we really need to check each and every one of them; if any of them are for resources rather than actual files, that's an issue.

**Comment by jskeet** [comment]
Any chance of this being addressed soon? It's proving very hard to work around at the moment. I could try to take a look myself, but with a lot less experience of the codebase, I suspect it's going to make it a lot slower for me to work out what's going on in each case.

**Comment by guptasu** [comment]
Hi John, I will look into this soon. I will not have time for next week, but can start this work early November.

**Comment by guptasu** [comment]
@jskeet, this should be fixed now. Let us know if you run into any issues related to api-compiler.
Thanks for reporting the issue.

Thanks @rcleveng  for fixing this.

-Sunny (Google Api Compiler Team)

**Comment by jskeet** [comment]
Thanks - will try it when I get the chance. (I haven't looked at how this gets pulled in from the toolkit project.)
