### ISSUE TITLE
Publish releases as jars with dependencies

### ISSUE THREAD

**Issue by kyessenov** [googleapis/api-compiler#21]
Please publish the released artifacts here on github.
The tool requires checking out the repo and is sensitive to which directory you run "run.sh".
It is a lot easier to just run java -jar api-compiler.jar.

**Comment by guptasu** [comment]
Hi Kuat,

Since you are already doing this work, I have assigned this issue to you. Let me know if you need anything from me. 

Thanks,
-Sunny

**Comment by guptasu** [comment]
Resolving this issue since for now all use cases are using api compiler from inception.
