### ISSUE TITLE
Inconsistent use of File.pathSeparator

### ISSUE THREAD

**Issue by jskeet** [googleapis/api-compiler#30]
`Location` assumes a :-separated name:

https://github.com/googleapis/api-compiler/blob/abfb87284cdeb8cdbd30187cf9ab833d6c68c54f/src/main/java/com/google/api/tools/framework/snippet/Location.java#L31

`SnippetParser.Input` creates a name based on `File.pathSeparator`:

https://github.com/googleapis/api-compiler/blob/abfb87284cdeb8cdbd30187cf9ab833d6c68c54f/src/main/java/com/google/api/tools/framework/snippet/SnippetParser.java#L104

The combination of these prevents the parser from working properly on Windows.

**Comment by jskeet** [comment]
(It's not clear to me whether it would be better to use `:` in both places of `File.pathSeparator` in both places. Either is probably fine, so long as it's consistent.)

**Comment by jskeet** [comment]
cc @garrettjonesgoogle and @geigerj - when this is fixed, I'd love to pick up a new version for toolkit.

**Comment by guptasu** [comment]
Is this breaking vkit use case?

**Comment by jskeet** [comment]
It breaks me running vkit's Java piece on "vanilla" Windows, yes. Currently my build script drops down to WSL (Windows Subsystem for Linux) to run the Linux version of Java, just for that step.
